-- =============================================================================
-- Migration 001: Create projects table
-- Project: Project Pulse
-- Run in: Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- =============================================================================

-- Enable pgvector extension (needed for Phase 2 RAG embeddings)
CREATE EXTENSION IF NOT EXISTS vector;

-- Enable UUID generation function
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- ENUM TYPES
-- =============================================================================

DO $$ BEGIN
    CREATE TYPE project_status AS ENUM (
        'active',
        'archived',
        'completed',
        'on_hold'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE project_tech_stack AS ENUM (
        'python',
        'typescript',
        'java',
        'rust',
        'go',
        'other'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- =============================================================================
-- TABLE: projects
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.projects (
    -- Primary Key: UUID v4 generated by the DB (not the client)
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Owning user (references auth.users when Supabase Auth is enabled)
    user_id         UUID            NOT NULL,

    -- Core fields
    name            VARCHAR(120)    NOT NULL,
    description     TEXT,
    status          project_status  NOT NULL DEFAULT 'active',
    tech_stack      project_tech_stack NOT NULL DEFAULT 'python',
    github_url      VARCHAR(500),

    -- Phase 2: RAG embedding (1536 dims = OpenAI text-embedding-3-small)
    -- Uncomment when you enable the pgvector extension and run Phase 2 migrations
    -- embedding       VECTOR(1536),

    -- Audit timestamps
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ

    -- NOTE: Add FK to auth.users when enabling Supabase Auth:
    -- CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- B-tree index on user_id for list_projects() O(log n) WHERE clause
CREATE INDEX IF NOT EXISTS idx_projects_user_id
    ON public.projects (user_id);

-- Composite index for sorted paginated listings (user scoped + time ordered)
CREATE INDEX IF NOT EXISTS idx_projects_user_created
    ON public.projects (user_id, created_at DESC);

-- Partial index for active projects only (most common filter)
CREATE INDEX IF NOT EXISTS idx_projects_user_active
    ON public.projects (user_id)
    WHERE status = 'active';

-- =============================================================================
-- TRIGGER: auto-update updated_at on every UPDATE
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON public.projects;
CREATE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON public.projects
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- UNIQUE CONSTRAINT: one project name per user
-- =============================================================================

ALTER TABLE public.projects
    DROP CONSTRAINT IF EXISTS uq_project_name_per_user;

ALTER TABLE public.projects
    ADD CONSTRAINT uq_project_name_per_user
    UNIQUE (user_id, name);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS) — Enable when Supabase Auth is active
-- =============================================================================

-- ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY "Users can view their own projects"
--     ON public.projects FOR SELECT
--     USING (auth.uid() = user_id);
--
-- CREATE POLICY "Users can create their own projects"
--     ON public.projects FOR INSERT
--     WITH CHECK (auth.uid() = user_id);
--
-- CREATE POLICY "Users can update their own projects"
--     ON public.projects FOR UPDATE
--     USING (auth.uid() = user_id);
--
-- CREATE POLICY "Users can delete their own projects"
--     ON public.projects FOR DELETE
--     USING (auth.uid() = user_id);

-- =============================================================================
-- VERIFICATION QUERY (run after migration to confirm table exists)
-- =============================================================================

SELECT
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'projects'
ORDER BY ordinal_position;
